### ISSUE TITLE
Add support for notification categories

### ISSUE THREAD

**Issue by muchtall** [nkgilley/python-join-api#12]
Notification categories allow the user the ability to set different notification profiles for each category (ie, sound, vibration, visibility, etc.). Really helpful when used with platforms like HomeAssistant so that you can set a different notification sound per the type of notification (ie, doorbell sound for doorbell automations).

I've already tested the code modifications. Just wanted to open an issue to tie to the pull request.

**Comment by nkgilley** [comment]
Thanks! version 0.0.9 is now available on pypi
