### ISSUE TITLE
Please add support for actions in notifcations

### ISSUE THREAD

**Issue by pstuifzand** [nkgilley/python-join-api#5]
Notifications can contain predefined actions. With this it's possible to send extra button to Join that the user can click and start an action.

For a description of how this is implemented see this page: https://joaoapps.com/join/actions/#notifications

**Comment by stephack** [comment]
I second this request. I have this configured on a driver I wrote in groovy for Hubitat.
https://github.com/stephack/Hubitat/blob/master/drivers/Join%20API%20Driver/Join%20API%20Driver.groovy

I would love to have thins functionality in Hassio as well.

**Comment by nkgilley** [comment]
added in 0.0.5
